# Logger Configuration
logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

# Web Server Configuration
server:
  port: 5150
  binding: localhost
  host: http://localhost
  middlewares:

# Background Worker Configuration
workers:
  mode: BackgroundAsync

# Initializers Configuration
initializers:
#  oauth2:
#    authorization_code: # Authorization code grant type
#      - client_identifier: google # Identifier for the OAuth2 provider. Replace 'google' with your provider's name if different, must be unique within the oauth2 config.
#        ... other fields
